version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - woyuen
  - abruere
  labels:
  - "type: Dependencies"
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: karma
    versions:
    - 6.0.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
